# Images Collection

In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
#read the dataset
df=pd.read_csv("train.csv")
df

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# 1

In [4]:
df1=df[df['label']==1]
df1.reset_index(drop=True, inplace=True)
df1=df1.drop('label',axis=1)
df1

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4679,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4680,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4681,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4682,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4683,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
df1.shape

(4684, 784)

In [ ]:
a=''
for i in range(200):
    array1=df1.loc[i].to_numpy()
    array1 = np.reshape(array1, (28, 28))
    plt.imshow(array1,cmap=plt.cm.binary)
    plt.axis("off")
    val=("%s%s" % (a, i))
    plt.savefig(('{}/'+val).format('captured_images/1'))

# 2

In [6]:
df2=df[df['label']==2]
df2.reset_index(drop=True, inplace=True)
df2=df2.drop('label',axis=1)
df2

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4172,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4173,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4174,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4175,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4176,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
df2.shape

(4177, 784)

In [ ]:
a=''
for i in range(200):
    array2=df2.loc[i].to_numpy()
    array2 = np.reshape(array2, (28, 28))
    plt.imshow(array2,cmap=plt.cm.binary)
    plt.axis("off")
    val=("%s%s" % (a, i))
    plt.savefig(('{}/'+val).format('captured_images/2'))

# 3

In [ ]:
df3=df[df['label']==3]
df3.reset_index(drop=True, inplace=True)
df3=df3.drop('label',axis=1)
df3

In [ ]:
df3.shape

In [ ]:
a=''
for i in range(200):
    array3=df3.loc[i].to_numpy()
    array3 = np.reshape(array3, (28, 28))
    plt.imshow(array3,cmap=plt.cm.binary)
    plt.axis("off")
    val=("%s%s" % (a, i))
    plt.savefig(('{}/'+val).format('captured_images/3'))

# 4

In [ ]:
df4=df[df['label']==4]
df4.reset_index(drop=True, inplace=True)
df4=df4.drop('label',axis=1)
df4

In [ ]:
df4.shape

In [ ]:
a=''
for i in range(200):
    array4=df4.loc[i].to_numpy()
    array4 = np.reshape(array4, (28, 28))
    plt.imshow(array4,cmap=plt.cm.binary)
    plt.axis("off")
    val=("%s%s" % (a, i))
    plt.savefig(('{}/'+val).format('captured_images/4'))

# 5

In [ ]:
df5=df[df['label']==5]
df5.reset_index(drop=True, inplace=True)
df5=df5.drop('label',axis=1)
df5

In [ ]:
df5.shape

In [ ]:
a=''
for i in range(200):
    array5=df5.loc[i].to_numpy()
    array5 = np.reshape(array5, (28, 28))
    plt.imshow(array5,cmap=plt.cm.binary)
    plt.axis("off")
    val=("%s%s" % (a, i))
    plt.savefig(('{}/'+val).format('captured_images/5'))

# 6

In [ ]:
df6=df[df['label']==6]
df6.reset_index(drop=True, inplace=True)
df6=df6.drop('label',axis=1)
df6

In [ ]:
df6.shape

In [ ]:
a=''
for i in range(200):
    array6=df6.loc[i].to_numpy()
    array6 = np.reshape(array6, (28, 28))
    plt.imshow(array6,cmap=plt.cm.binary)
    plt.axis("off")
    val=("%s%s" % (a, i))
    plt.savefig(('{}/'+val).format('captured_images/6'))

# 7

In [ ]:
df7=df[df['label']==7]
df7.reset_index(drop=True, inplace=True)
df7=df7.drop('label',axis=1)
df7

In [ ]:
df7.shape

In [ ]:
a=''
for i in range(00):
    array7=df7.loc[i].to_numpy()
    array7 = np.reshape(array7, (28, 28))
    plt.imshow(array7,cmap=plt.cm.binary)
    plt.axis("off")
    val=("%s%s" % (a, i))
    plt.savefig(('{}/'+val).format('captured_images/7'))

# 8

In [ ]:
df8=df[df['label']==8]
df8.reset_index(drop=True, inplace=True)
df8=df8.drop('label',axis=1)
df8

In [ ]:
df8.shape

In [ ]:
a=''
for i in range(200):
    array8=df8.loc[i].to_numpy()
    array8 = np.reshape(array8, (28, 28))
    plt.imshow(array8,cmap=plt.cm.binary)
    plt.axis("off")
    val=("%s%s" % (a, i))
    plt.savefig(('{}/'+val).format('captured_images/8'))

# 9

In [ ]:
df9=df[df['label']==9]
df9.reset_index(drop=True, inplace=True)
df9=df9.drop('label',axis=1)
df9

In [ ]:
df9.shape

In [ ]:
a=''
for i in range(200):
    array9=df9.loc[i].to_numpy()
    array9 = np.reshape(array9, (28, 28))
    plt.imshow(array9,cmap=plt.cm.binary)
    plt.axis("off")
    val=("%s%s" % (a, i))
    plt.savefig(('{}/'+val).format('captured_images/9'))

# 0

In [ ]:
df0=df[df['label']==0]
df0.reset_index(drop=True, inplace=True)
df0=df0.drop('label',axis=1)
df0

In [ ]:
df0.shape

In [ ]:
a=''
for i in range(200):
    array0=df0.loc[i].to_numpy()
    array0 = np.reshape(array0, (28, 28))
    plt.imshow(array0,cmap=plt.cm.binary)
    plt.axis("off")
    val=("%s%s" % (a, i))
    plt.savefig(('{}/'+val).format('captured_images/0'))